package hu.helixlab.tracking.entity;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", schema = "public")
public class UserRole extends BaseEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7287912198064226484L;
	private int userRoleId;
	private Roles roles;
	private Users users;

	public UserRole() {
	}

	public UserRole(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRole(int userRoleId, Roles roles, Users users) {
		this.userRoleId = userRoleId;
		this.roles = roles;
		this.users = users;
	}

	@Id
	@SequenceGenerator(name="user_role_user_role_id_seq", sequenceName="user_role_user_role_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.AUTO, generator="user_role_user_role_id_seq")

	@Column(name = "user_role_id", unique = true, nullable = false)
	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Override
	public String toString() {
		return "UserRole [userRoleId=" + userRoleId + ", roles=" + roles + ", users=" + users + "]";
	}
	

}
